apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  mongodb-username: bW9uZ29hZG1pbg==
  mongodb-password: UGFzc3dvcmQx
  mongodb-root-password: UGFzc3dvcmQx
  mongodb-database: Y2Fyc19yZXN0X2FwaQ==
